query AccountWithEntries($id: UUID!, $after: String) {
  account(id: $id) {
    name
    entries(first: 1, after: $after) {
      nodes {
        transactionId
        units
        currency
        createdAt
      }

      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}
