[package]
name = "cala-ledger-outbox-client"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
prost-wkt-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.10.2", features = ["prost"] }
