[package]
name = "cala-ledger-outbox-client"
version = "0.1.0"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
cala_types = { path = "../cala-ledger-core-types", package = "cala-ledger-core-types" }
cala-cel-interpreter = { path = "../cala-cel-interpreter" }

futures = { workspace = true }
uuid = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tracing = { workspace = true }
prost-wkt-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[build-dependencies]
protobuf-src = { version = "1.1.0" }
tonic-build = { version = "0.11.0", features = ["prost"] }
