-- Supports `EffectiveBalances::list_modified_since`: a CDC-style query that
-- enumerates cumulative-effective-balance rows written since a caller-held
-- watermark, scoped to one journal.
--
-- The `updated_at` column (bound from `EffectiveBalanceSnapshot.modified_at`
-- in `EffectiveBalanceRepo::insert_new_snapshots`), not `created_at`, is the
-- correct watermark column: `created_at` is set once at row-genesis for a
-- given (account_id, currency) chain (`EffectiveBalanceData::first_snapshot`)
-- and is carried forward unchanged on every later row for that chain
-- (`EffectiveBalanceData::into_snapshots` copies it straight from the
-- carried-forward in-memory baseline) — it does NOT mark per-row insert
-- time. `updated_at` is what `EffectiveBalanceData::update_snapshot`
-- refreshes on every write, including backdating-rewritten rows, via the
-- same threaded `created_at: DateTime<Utc>` parameter passed into
-- `re_calculate_snapshots` (see spec-effective-balance-list-modified-since.md
-- for the detailed writeup of this discrepancy).
--
-- The daily-cadence `updated_at >= since` window is narrow, so a
-- `(journal_id, updated_at)` index is sufficient for the initial row
-- filter — the post-filter DISTINCT ON over one day's changes does not
-- need a covering index on top.
CREATE INDEX idx_cala_cumulative_effective_balances_journal_updated_at
    ON cala_cumulative_effective_balances (journal_id, updated_at);
