mutation addToAccountSet($input: AddToAccountSetInput!) {
  addToAccountSet(input: $input) {
   accountSet{
      accountSetId
      name
      balance(currency: "USD") {
        settled {
          normalBalance {
            units
          }
        }
      }
    }
  }
}
