version: "3"
services:
  integration-deps:
    image: busybox
    depends_on:
    - postgres
  postgres:
    image: postgres:14.1
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
