services:
  integration-deps:
    image: busybox
    depends_on:
    - server-pg
  server-pg:
    image: postgres:16.4
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
