/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class CalaAccount {
  id(): string
  values(): AccountValues
}

export declare class CalaAccounts {
  create(newAccount: NewAccount): Promise<CalaAccount>
  list(query: PaginatedQueryArgs): Promise<PaginatedAccounts>
}

export declare class CalaJournal {
  id(): string
  values(): JournalValues
}

export declare class CalaJournals {
  create(newJournal: NewJournal): Promise<CalaJournal>
}

export declare class CalaLedger {
  static connect(config: CalaLedgerConfig): Promise<CalaLedger>
  accounts(): CalaAccounts
  journals(): CalaJournals
  awaitOutboxServer(): Promise<void>
}

export interface AccountValues {
  id: string
  code: string
  name: string
  externalId?: string
  description?: string
  metadata?: any
}

export interface CalaLedgerConfig {
  pgCon: string
  maxConnections?: number
  outbox?: OutboxServerConfig
}

export interface CursorToken {
  token: string
}

export interface JournalValues {
  id: string
  name: string
  description?: string
}

export interface NewAccount {
  id?: string
  code: string
  name: string
  externalId?: string
  description?: string
  metadata?: any
}

export interface NewJournal {
  id?: string
  name: string
  externalId?: string
  description?: string
}

export interface OutboxServerConfig {
  enabled: boolean
  listenPort?: number
}

export interface PaginatedAccounts {
  accounts: Array<AccountValues>
  hasNextPage: boolean
  endCursor?: CursorToken
}

export interface PaginatedQueryArgs {
  after?: CursorToken
  first: number
}
