/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NewAccount {
  id?: string
  code: string
  name: string
  externalId?: string
  description?: string
  tags?: Array<string>
}
export interface CalaLedgerConfig {
  pgCon: string
  maxConnections?: number
}
export class CalaAccounts {
  create(newAccount: NewAccount): Promise<string>
}
export class CalaLedger {
  static connect(config: CalaLedgerConfig): Promise<CalaLedger>
  accounts(): CalaAccounts
}
