query accountSetWithBalance($accountSetId: UUID!, $currency: CurrencyCode!) {
  accountSet(id: $accountSetId) {
    name
    journalId
    balance(currency: $currency) {
      settled {
        normalBalance {
          units
        }
      }
    }
  }
}
