[package]
name = "cala-ledger"
description = "An embeddable double sided accounting ledger built on PG/SQLx"
repository = "https://github.com/GaloyMoney/cala"
documentation = "https://docs.rs/cala-ledger"
readme = "../README.md"
version = "0.1.0-dev"
edition = "2021"
license = "Apache"
categories = ["accounting", "ledger"]

[features]

fail-on-warnings = []

[dependencies]
chrono = { workspace = true }
derive_builder = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
