apiVersion: vendir.k14s.io/v1alpha1
kind: Config

# Relative to ci/
directories:
- path: ../.github/workflows/vendor
  contents:
  - path: . # Copy this folder out to ..
    git:
      url: https://github.com/GaloyMoney/galoy-concourse-shared.git
      ref: 8aaee2b5105fe0d131292f3f3c7ace40741a0c61
    includePaths:
    - shared/actions/*
    excludePaths:
    - shared/actions/nodejs-*
    - shared/actions/docker-*
    - shared/actions/chart-*
    newRootPath: shared/actions

- path: ./vendor
  contents:
  - path: .
    git:
      url: https://github.com/GaloyMoney/galoy-concourse-shared.git
      ref: 8aaee2b5105fe0d131292f3f3c7ace40741a0c61
    includePaths:
    - shared/ci/**/*
    excludePaths:
    - shared/ci/**/nodejs-*
    - shared/ci/**/chart-*
    - shared/ci/**/docker-*
    newRootPath: shared/ci
