[package]
name = "cala-ledger-example-rust"
version = "0.4.6-dev"
edition = "2021"
workspace = "../../"

[dependencies]
cala-ledger = { path = "../../cala-ledger" }

anyhow = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
rand = "0.9"
