[package]
name = "test-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
cala-extension = { path = "../../cala-extension" }

async-graphql = { workspace = true, features = ["dynamic-schema"] }
