name: "Integration Tests"

on:
  pull_request:
    branches: [main]

jobs:
  integration:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Run the Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: nix run .#nextest

