name: Website test deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - 'website/**'

jobs:
  test-deploy:
    name: Test Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v16
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd website
          nix-shell -p yarn --run "yarn install --frozen-lockfile"
      - name: Test Build
        run: |
          cd website
          nix-shell -p yarn --run "yarn build"
